{% set name = "isofit" %}
{% set version = "2.10.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/isofit-{{ version }}.tar.gz
  sha256: 6769a6f6b109e20bb49d6d63d9bd3b3419d824bfd0e5960c8164892493619f76

build:
  noarch: python
  number: 3
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - click
    - gdal >=2.0.0
    - matplotlib-base >=2.2.2
    - numpy >=1.20
    - pandas >=0.24.0
    - pep8 >=1.7.1
    - pygrib
    - pytest >=3.5.1
    - python >=3.8
    - python-xxhash >=1.2.0
    - pyyaml >=5.3.2
    - ray-default
    - scikit-image >=0.17.0
    - scikit-learn >=0.19.1
    - scipy >=1.3.0
    - setuptools
    - spectral >=0.19
    - utm
    - tensorflow >=2.0.1

test:
  imports:
    - isofit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/{{ name }}/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Imaging Spectrometer Optimal FITting (ISOFIT)
  description: |
    ISOFIT contains a set of routines and utilities for fitting surface, 
    atmosphere and instrument models to imaging spectrometer data
  dev_url: https://github.com/{{ name }}/{{ name }}
  doc_url: https://github.com/{{ name }}/{{ name }}/wiki
  doc_source_url: https://github.com/{{ name }}/{{ name }}/tree/master/docs

extra:
  recipe-maintainers:
    - unbohn
    - pgbrodrick
    - davidraythompson
