{% set name = "isofit" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/isofit-{{ version }}.tar.gz
  sha256: 9f2f7bf74ad189858451328cdb6423a7e1e6cb018489eec60f8fa572cddf8f41

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - click
    - dask
    - h5py
    - netCDF4
    - numpy >=1.20
    - pandas >=0.24.0
    - pep8 >=1.7.1
    - pygrib
    - pytest >=3.5.1
    - python >=3.8
    - python-xxhash >=1.2.0
    - pyyaml >=5.3.2
    - ray-default
    - scikit-image >=0.17.0
    - scikit-learn >=0.19.1
    - scipy >=1.3.0
    - spectral >=0.19
    - utm
    - xarray <2024.1.1

test:
  imports:
    - isofit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/{{ name }}/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Imaging Spectrometer Optimal FITting (ISOFIT)
  description: |
    ISOFIT contains a set of routines and utilities for fitting surface, 
    atmosphere and instrument models to imaging spectrometer data
  dev_url: https://github.com/{{ name }}/{{ name }}
  doc_url: https://github.com/{{ name }}/{{ name }}/wiki
  doc_source_url: https://github.com/{{ name }}/{{ name }}/tree/master/docs

extra:
  recipe-maintainers:
    - unbohn
    - pgbrodrick
    - davidraythompson
