{% set name = "isofit" %}
{% set version = "2.9.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/isofit-{{ version }}.tar.gz
  sha256: a0da551073765dd2ad093b7772a8362b88150c472ccd6edaabc320cddc267cd5 

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - setuptools
    - numpy >=1.20
    - matplotlib-base >=2.2.2
    - scipy >=1.3.0
    - scikit-learn >=0.19.1
    - scikit-image >=0.17.0
    - spectral >=0.19
    - pytest >=3.5.1
    - pep8 >=1.7.1
    - python-xxhash >=1.2.0
    - pyyaml >=5.3.2
    - ray-all >=1.2.0
    - pandas >=0.24.0
    - gdal >=2.0.0
    - tensorflow >=2.0.1

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/{{ name }}/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Imaging Spectrometer Optimal FITting (ISOFIT)'
  description: |
    ISOFIT contains a set of routines and utilities for fitting surface, 
    atmosphere and instrument models to imaging spectrometer data
  dev_url: https://github.com/{{ name }}/{{ name }}
  doc_url: https://github.com/{{ name }}/{{ name }}/wiki
  doc_source_url: https://github.com/{{ name }}/{{ name }}/tree/master/docs

extra:
  recipe-maintainers:
    - unbohn
    - pgbrodrick
    - davidraythompson
