{% set name = "isofit" %}
{% set version = "3.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/isofit-{{ version }}.tar.gz
  sha256: 652c904557aac4bb1905bc3b935d758fb705265d5c41dfdaaa468be39bccc2c6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
  run:
    - click
    - dask
    - h5py <=3.14.0
    - netCDF4 <1.7.4
    - numpy >=1.20
    - pep8 >=1.7.1
    - pytest >=3.5.1
    - python >={{ python_min }}
    - python-xxhash <3
    - pytorch-cpu
    - pyyaml >=5.1.2
    - ray-default
    - scikit-image >=0.17.0
    - scikit-learn >=0.19.1
    - scipy >=1.3.0
    - spectral >=0.19
    - xarray
    - zarr >=2,<3

test:
  imports:
    - isofit
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/{{ name }}/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Imaging Spectrometer Optimal FITting (ISOFIT)
  description: |
    ISOFIT contains a set of routines and utilities for fitting surface, 
    atmosphere and instrument models to imaging spectrometer data
  dev_url: https://github.com/{{ name }}/{{ name }}
  doc_url: https://github.com/{{ name }}/{{ name }}/wiki
  doc_source_url: https://github.com/{{ name }}/{{ name }}/tree/master/docs

extra:
  recipe-maintainers:
    - unbohn
    - pgbrodrick
    - davidraythompson
